services:
  storage:
    image: postgres
    restart: always
    networks:
      - storage-network
    volumes:
      - ${PWD}/storage-data:/storage-data:rw
    configs:
      - postgres-config
    secrets:
      - postgres-password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      PGDATA: /storage-data
    command: postgres -c config_file=/postgres-config


secrets:
  postgres-password:
    file: ./secrets/postgres-password

configs:
  postgres-config:
    file: ./configs/postgresql.conf


networks:
  storage-network: