# Generated by Django 2.0.5 on 2018-05-18 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_dat',
            new_name='pub_date',
        ),
    ]
